from pathlib import Path
root=Path('whisper/examples/whisper.android.java'); app=root/'app'
# Gradle
g=(app/'build.gradle').read_text();g=g.replace('applicationId "com.litongjava.whisper.android.java"','applicationId "org.pavel.tabspeech.whisper"').replace('minSdkVersion 21','minSdkVersion 26').replace('targetSdkVersion 31','targetSdkVersion 28').replace('versionCode 1','versionCode 2').replace('versionName "1.0"','versionName "0.2"');g=g.replace('  compileOptions {',"  aaptOptions {\n    noCompress 'bin'\n  }\n  compileOptions {");(app/'build.gradle').write_text(g)
# Manifest: deliberately no INTERNET permission.
(app/'src/main/AndroidManifest.xml').write_text('''<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.litongjava.whisper.android.java">\n<uses-permission android:name="android.permission.RECORD_AUDIO"/><uses-permission android:name="android.permission.FOREGROUND_SERVICE"/><uses-permission android:name="android.permission.WAKE_LOCK"/><uses-permission android:name="android.permission.BLUETOOTH"/><uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/><uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>\n<application android:allowBackup="false" android:label="TabSpeech Whisper" android:theme="@style/Theme.AppCompat.Light.NoActionBar"><activity android:name=".MainActivity" android:screenOrientation="portrait" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><service android:name=".ListenService" android:exported="false"/></application></manifest>''')
# Copy custom Java UI/service from the build branch.
pkg=app/'src/main/java/com/litongjava/whisper/android/java';pkg.mkdir(parents=True,exist_ok=True)
(pkg/'MainActivity.java').write_text(Path('tabspeech/MainActivity.java').read_text());(pkg/'ListenService.java').write_text(Path('tabspeech/ListenService.java').read_text())
# JNI language argument; audio remains float[] in memory.
p=app/'src/main/jni/whisper/jni.c';s=p.read_text();old='''Java_com_whispercpp_java_whisper_WhisperLib_fullTranscribe(\n        JNIEnv *env, jobject thiz, jlong context_ptr, jint num_threads, jfloatArray audio_data) {''';new='''Java_com_whispercpp_java_whisper_WhisperLib_fullTranscribe(\n        JNIEnv *env, jobject thiz, jlong context_ptr, jint num_threads, jfloatArray audio_data, jstring language_str) {''';assert old in s;s=s.replace(old,new);old2='''    params.language = "en";\n    params.n_threads = num_threads;''';new2='''    const char *language = (*env)->GetStringUTFChars(env, language_str, NULL);\n    params.language = language;\n    params.n_threads = num_threads;''';assert old2 in s;s=s.replace(old2,new2);needle='''    (*env)->ReleaseFloatArrayElements(env, audio_data, audio_data_arr, JNI_ABORT);\n}''';repl='''    (*env)->ReleaseStringUTFChars(env, language_str, language);\n    (*env)->ReleaseFloatArrayElements(env, audio_data, audio_data_arr, JNI_ABORT);\n}''';assert needle in s;s=s.replace(needle,repl,1);p.write_text(s)
# Java native signature and context method. Keep the original one-argument overload for upstream example classes.
p=app/'src/main/java/com/whispercpp/java/whisper/WhisperLib.java';s=p.read_text();s=s.replace('public static native void fullTranscribe(long contextPtr, int numThreads, float[] audioData);','public static native void fullTranscribe(long contextPtr, int numThreads, float[] audioData, String language);');p.write_text(s)
p=app/'src/main/java/com/whispercpp/java/whisper/WhisperContext.java';s=p.read_text();s=s.replace('public String transcribeData(float[] data) throws ExecutionException, InterruptedException {','public String transcribeData(float[] data, String language) throws ExecutionException, InterruptedException {',1);s=s.replace('WhisperLib.fullTranscribe(ptr, numThreads, data);','WhisperLib.fullTranscribe(ptr, numThreads, data, language);',1);s=s.replace('WhisperLib.fullTranscribe(ptr, numThreads, data);','WhisperLib.fullTranscribe(ptr, numThreads, data, "en");');marker='''  public String transcribeData(float[] data, String language) throws ExecutionException, InterruptedException {''';compat='''  public String transcribeData(float[] data) throws ExecutionException, InterruptedException {\n    return transcribeData(data, "en");\n  }\n\n'''+marker;assert marker in s;s=s.replace(marker,compat,1);p.write_text(s)
print('TabSpeech patch complete')
